### ISSUE TITLE
Support simple drivers (observable in, observable out)

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/cycle-restart#18]
Funnily enough, I currently support drivers that have selector functions like `@cycle/dom` and drivers where the provided `sources` is an observable of observables (like `@cycle/dom`). 

Some good candidates: `@cycle/storage` and `cycle-animation-driver`

**Comment by SkaterDad** [comment]
Just tried this out with `@cycle/history` and get an error on initialization:
`Uncaught TypeError: event.do is not a function`

The app will start fine if I don't wrap the History driver in `restartable()`, however that prevents the HMR from working (webpack console logs an error about an observable being disposed).

I hope this info is helpful!

**Comment by Widdershin** [comment]
Thanks for the report @SkaterDad, I'll take a crack at adding support for `@cycle/history`

**Comment by Widdershin** [comment]
@SkaterDad: Just added support for `@cycle/history` in 6f6d6ca8ca07c8d4a71 (released as v0.0.4).

Could you try it out and see if it works for your use case?

**Comment by SkaterDad** [comment]
I no longer get any console errors, but am having other issues which are likely unrelated.  My HTTP requests are no longer getting subscribed after I wrap them in `restartable`, my DOM doesn't update, and all of the DOM event listeners seems to be disconnected after the hot module update (I am using `cycle-snabbdom`, btw).  I can open another issue if you prefer.

Normal hot module updates work perfectly well.
Here's a link to my attempt, hopefully I just have it set up wrong:
https://github.com/SkaterDad/cycle-snabbdom-examples/blob/url-routing/src/index.restartable.js

**Comment by Widdershin** [comment]
Hmmm, I tried out your app and I'm getting an error about `res$.request` not being defined (when I try the github search), which I think is a legit bug. Are you seeing that?

**Comment by SkaterDad** [comment]
I'm seeing the same error (on v0.0.5 now).

To make it easier to A/B test, I made another webpack config and npm script (in url-routing branch, still).
 * `npm run dev` will do the more crude hot reloading.  Everything seems to work, even after reloads.
 * `npm run exp` will use cycle-restart.

The two examples in my app which use HTTP are "Github Search" and "Hero Complex".  Neither of them seem to be working.

Hero Complex is supposed to fire off an HTTP request immediately on page load, but it seems like the HTTP driver never fires off the request.

**Comment by Widdershin** [comment]
@SkaterDad could you please try with the newly released v0.0.6, res$.request should now be available.
I tried to set it up for the latest version of your example but couldn't get the server up and running.

**Comment by SkaterDad** [comment]
Sorry about that, I've been doing a lot of experimenting with server side
rendering with hot module replacement, so it's semi broken at the moment.
I should be able to test your new version within a day or so.

**Comment by Widdershin** [comment]
No worries :smile: 

Let me know how it goes.

**Comment by SkaterDad** [comment]
Finally got around to this.  The url-routing branch has these npm scripts which are functional:
 * `npm run exp` runs the _cycle-restart_ version of the app.
 * `npm run hot-client` runs the standard normal hot reloading.

`client.restart.js` is the entry point for the `exp` mode.

`http://localhost:3000/github` and `http://localhost:3000/hero-complex` are the test pages for HTTP.

I get errors again, due to `res$.request` not being available when trying to filter HTTP responses.

I put some `console.dir(res$)` in the filter methods so you can see it.

```
TapObservable
  _oC: undefined
  _oE: undefined
  _oN: function (response)
  source: AnonymousObservable
  __proto__: __
```

I double checked that I'm on 0.0.6, so I'm not sure why this is still not working?

**Comment by Widdershin** [comment]
Hey @SkaterDad, I've had a go and it seems like it's working on the latest version, `0.0.9`. Could you give it a try and let me know?

I noticed an issue where the app was still making HTTP requests on restart, but that might be a known limitation. Are you debouncing or delaying requests?

**Comment by Widdershin** [comment]
I'm closing this issue as cycle-restart works for me in this project. Please reopen this issue if you are still having trouble.
