### ISSUE TITLE
npm missing 'lib' directory (v.0.0.2)

### ISSUE THREAD

**Issue by SkaterDad** [Widdershin/cycle-restart#19]
I believe the npm package needs to have the built `lib` folder.  Webpack is throwing `Module not found` errors when I try to import it.

Thanks!

I look forward to giving this a try with my example app.  Have you tried this with `@cycle/history` yet?

**Comment by Widdershin** [comment]
Thanks, fixed in f7b1070357ab71c15ec61c90076618dc467a64ba !
