### ISSUE TITLE
Support read-only and write-only drivers

### ISSUE THREAD

**Issue by staltz** [Widdershin/cycle-restart#24]
I'm all excited here putting hot reloading in a certain app. I noticed a bug because the `restart` code assumes every driver will return (sources), and that's not true. Some drivers only take in sinks (e.g. a console log driver) and some drivers only return sources (e.g. a read-only websocket driver). We need to support those, so we need to add some basic null/undefined check.

**Comment by Widdershin** [comment]
Is there a specific driver that exhibits problems that I can write a test against?

**Comment by Widdershin** [comment]
I've released v0.0.5 to address this issue @staltz, please let me know if you run into any other issues :)

**Comment by staltz** [comment]
Cool! The test driver would be in cycle-examples/autocomplete-search, it's the preventDefault driver.
