### ISSUE TITLE
Cannot set property 'isDisposed ' of undefined

### ISSUE THREAD

**Issue by edge** [Widdershin/cycle-restart#35]
This error causes webpack to ditch the reload:

![http://i.imgur.com/A43npmO.png](http://i.imgur.com/A43npmO.png)

This happens inside of a certain function that was given to `onDispose` in `restartable`, which traces the error either to https://github.com/Widdershin/cycle-restart/blob/master/src/restartable.js#L154 or https://github.com/Widdershin/cycle-restart/blob/master/src/restartable.js#L98.

repro: https://github.com/edge/cyc/tree/restart

**Comment by Widdershin** [comment]
I've released v0.0.10 to address this issue.

I've tested that it works with cyc, that was a very helpful repro case.

I made a pull request to upgrade cycle-restart. https://github.com/edge/cyc/pull/7

Could you please give it a go and let me know if that fixes it for you?

**Comment by edge** [comment]
Got it to work.

**Comment by Widdershin** [comment]
Awesome! I think cyc is the easiest way to get started with hot reloading at the moment. We should add some info to the readme about that.

**Comment by edge** [comment]
cc @staltz :)

**Comment by staltz** [comment]
@edge can you submit a PR to cyclejs.github.io in the Getting Started page to add a reference to `cyc`?
