### ISSUE TITLE
TypeError: Cannot read property 'onNext' of undefined

### ISSUE THREAD

**Issue by ronag** [Widdershin/cycle-restart#38]
I'm having trouble figuring out why this error occurs during hot-reloading of only DOM?

Any ideas?

```
Uncaught TypeError: Cannot read property 'onNext' of undefined(anonymous function) @ restartable.js:219
run @ rx.all.js:11214
ScheduledItem.invokeCore @ rx.all.js:980
ScheduledItem.invoke @ rx.all.js:968
Rx.VirtualTimeScheduler.VirtualTimeSchedulerPrototype.start @ rx.all.js:11124
(anonymous function) @ restart.js:64
```

**Comment by Widdershin** [comment]
Hiya! Could you include the solution you found in this issue so anyone searching in future has an idea what to try?

**Comment by ronag** [comment]
Basically it's a problem when you have drivers that don't properly support restartable which causes some DOM elements in the DOM driver history not to exists.

Adding an assertion would make this much simpler to debug:

```javascript
streams[historicEvent.identifier].onNext(historicEvent.event);
```

**Comment by Widdershin** [comment]
Could you provide me with that driver? I'll add a test for a more informative error message

**Comment by ronag** [comment]
@Widdershin: Not yet, I have 8 drivers and I'm unsure what's causing it at the moment.

**Comment by ronag** [comment]
@Widdershin: Ok, this is spooky. I fixed the issue by making sure that all my `isolate` calls provide an explicit scope.

It seems that when hot reloading the scope names are not guaranteed to be exactly the same.

It might be due to the driver replaying in different order or something?

**Comment by Widdershin** [comment]
That's strange. Are you passing `isolate` as the last argument to `restart`? You shouldn't need to provide explicit scopes if that's the case.

Could you link me the code if it's public?

**Comment by ronag** [comment]
@Widdershin: Sorry, the code is not public.

**Comment by ronag** [comment]
Ok, using explicit scopes doesn't work either. For some reason all `DOM.select` streams start duplicating messages.

**Comment by ronag** [comment]
With the logging using the following assertions: https://github.com/Widdershin/cycle-restart/pulls

I get these kinds of errors...

```
Missing replay stream  .cycle-scope-cycle1/.cycle-scope-cycle4/.cycle-scope-grid/.cycle-scope-cycle13/.poster/load(anonymous function) @ restartable.js:220run @ rx.all.js:11214ScheduledItem.invokeCore @ rx.all.js:980ScheduledItem.invoke @ rx.all.js:968Rx.VirtualTimeScheduler.VirtualTimeSchedulerPrototype.start @ rx.all.js:11124(anonymous function) @ restart.js:64
restartable.js:220 Missing replay stream  .cycle-scope-cycle1/.cycle-scope-cycle4/.cycle-scope-grid/.cycle-scope-cycle12/.poster/load(anonymous function) @ restartable.js:220run @ rx.all.js:11214ScheduledItem.invokeCore @ rx.all.js:980ScheduledItem.invoke @ rx.all.js:968Rx.VirtualTimeScheduler.VirtualTimeSchedulerPrototype.start @ rx.all.js:11124(anonymous function) @ restart.js:64
```

**Comment by ronag** [comment]
Ok, this was because of a side effect in the drivers that wasn't reset on dispose:

Maybe we should have a section of common issues in the README until we have better assertion and warnings?

Basically what I was doing is:

```javascript
export function makeSearchDriver(options, { NATS }) {
  const cache = new LRU({
    max: 1024,
  })

  return (request$) => {
    const nats = NATS(request$
      .map(({ query }) => ({
        subject: 'search.get',
        data: { query: query.trim() },
      }))
    )

    return {
      dispose() {
        nats.dispose()
      },
      reconnect$: Observable
        .merge([
          nats.reconnect$,
          nats.select('search.init'),
        ]),
      select(query) {
        query = query.trim()
        const hash = md5(query)

        return Observable
          .of(cache.get(hash))
          .filter(x => x)
          .concat(nats
            .select(`search.value.${hash}`)
            .map(x => x.data && x.data.result)
          )
          .do(x => cache.set(hash, x))
          .distinctUntilChanged(x => x, _.isEqual)
          .shareReplay(1)
      },
    }
  }
}
```

Note the `cache`.

I needed to clear it in dispose:

```javascript

      dispose() {
        cache.reset()
        nats.dispose()
      },
```
