### ISSUE TITLE
rerun vs restart?

### ISSUE THREAD

**Issue by ronag** [Widdershin/cycle-restart#48]
Noticed we now have both `rerun` and `restart`. What's the difference? When should on be used over the other?

**Comment by Widdershin** [comment]
@ronag for now, I would suggest you use `rerun`, as it handles passing sources and sinks from one run to another. For more information, have a look at @edge's pull request #46.

`restart` is now more of an implementation detail, and it might be removed from the public interface in future.

**Comment by edge** [comment]
@ronag @Widdershin I'll add API docs sometime soon.

**Comment by Widdershin** [comment]
Great :smile:
