### ISSUE TITLE
Support for Cycle.js ^7.0.0?

### ISSUE THREAD

**Issue by niieani** [Widdershin/cycle-restart#57]
Any news on supporting cycle-restart with the latest "diversity" iteration of Cycle.js? Perhaps with xstream? Thanks!

**Comment by Widdershin** [comment]
Definitely planned, note the issues tagged with "Cycle.js Diversity". 

Just need to find a couple of days to get stuck in, which is a bit hard with a full time job.

I hope to find time soon.

**Comment by Widdershin** [comment]
I have made some good progress towards an xstream based `cycle-restart`, the first step towards a diversity ready tool. The test suite for core features for DOM reloading is passing, and I'm now getting stuck into HTTP and the rest of the failing tests.

Anyone who is interested can follow my progress in #58

**Comment by TylorS** [comment]
I've been watching your progress @Widdershin really great stuff, keep up the amazing work :heart:

**Comment by Widdershin** [comment]
Update for anyone interested: `cycle-restart` works with diversity + xstream for `DOM` and `HTTP` at least. However, I am awaiting a fix for https://github.com/cyclejs/cyclejs/issues/476 before I can release.

Manually applying the fix from https://github.com/cyclejs/cyclejs/pull/477 means that all tests pass in #58.

**Comment by Widdershin** [comment]
Actually landed diversity support a while ago but today I landed support for unified, thanks to @wyqydsyq.
