### ISSUE TITLE
DOM is alternatingly wiped and restored upon HMR updates

### ISSUE THREAD

**Issue by wyqydsyq** [Widdershin/cycle-restart#62]
Going by my project here: https://github.com/wyqydsyq/unicycle

HMR itself seems to be configured fine, if I make changes to a file the HMR client will output that the relevant dependency graph has changed, the HMR update seems to contain the correct data, but when attempting to mount the new code it wipes the DOM underneath my app's mount point.

On the first update from HMR my app's DOM gets wiped completely (the node it was mounted to is left intact but has no children), on the second update I get an error in the console about `Cannot read property 'removeChild' of null` but my app's DOM gets correctly mounted based on the most recent update. It alternates between these two states.

Initial page load, everything is fine:
http://i.imgur.com/9oxdSdL.png

After first change (added an `!` to the end of the text), DOM breaks:
http://i.imgur.com/JqsjyhA.png

After second change (added another `!` to the end of the text), DOM is restored based on new code:
http://i.imgur.com/elYuxIF.png

This could very likely be just me doing something stupid, but this issue only surfaced when I updated Cycle and related packages to Unified versions and none of my config tinkering seems to have helped.

**Comment by wyqydsyq** [comment]
I've been able to reproduce this issue by updating the example to the latest versions of Cycle & co
https://github.com/wyqydsyq/cycle-restart/tree/feature/cycle-unified

**Comment by wyqydsyq** [comment]
@Widdershin I've located what's triggering this:
https://github.com/wyqydsyq/cycle-restart/blob/feature/cycle-unified/src/restart.js#L72

Seems calling the old `dispose()` is causing the DOM driver to freak out. I'm unsure if it's happening because it's wrapped in that `setTimeout()` (should this be changed to use the method from the Time driver?) or if calling `dispose()` simply isn't necessary with new versions of Cycle.

Either way, commenting out that line makes cycle-restart work perfectly for me in the example and does not seem to have introduced any regressions, but I haven't checked other drivers since the example is only using DOM.

I'll reproduce this change in my own project (which is using DOM, History and  HTTP) to see if removing the `dispatch()` causes any issues.

**Comment by Widdershin** [comment]
Should be addressed by the `v0.2.0` release 😄
