### ISSUE TITLE
Isolate support breaks in real world applications because of impurity

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/cycle-restart#8]
As seen in https://github.com/Widdershin/cycle-hot-reloading-example/commit/b5c18b372f5bcbbabac378d31a7b27cf1d7e6496

[Here is a gif that demonstrates the problem](https://gfycat.com/PleasedGlaringBonobo)

![gif](https://fat.gfycat.com/PleasedGlaringBonobo.gif)

This is because repeated calls to `isolate` without an explicit scope produce different results.

It seems like either we need to reset the value of `isolate` when we reload the code, or `cycle-restart` needs to account for the increase in values.

It seems tricky (with the current implementation of `isolate`) to reset it on code reload. @staltz @frikki you folk got any ideas?

**Comment by staltz** [comment]
Getting `isolate()` perfect is top priority for me. Right now I'm looking into other `isolate` issues in Cycle DOM recently pointed out by @laszlokorte, but this one comes next.

**Comment by Widdershin** [comment]
@staltz I think I will try adding an `isolate.reset()` function to set the `isolateCount` back to `0`, and then call that prior to restarting the application. I'm not sure if modules share state when imported in many places, so that approach might fall flat.

**Comment by laszlokorte** [comment]
Is there a strong reason why isolate's second parameter is optional? I think in almost all cases you would be able (and would want) to provide a custom namespace.

**Comment by Frikki** [comment]
@laszlokorte I, for one, has never wanted to provide a custom namespace.

**Comment by Widdershin** [comment]
Okay, so, status update time:

I've tried adding `isolate.reset()`, but it seems that import semantics prevent this from working. Perhaps using peer dependencies would allow this to work correctly, at least for browserify and webpack.

I managed to hack together a different approach, which is to automatically increment all of the scope ids recorded in selectors when restarting the application, but that approach is very hacky and fragile. (954158d918724588ec55ad5ac10cbba6f676d103)

We can achieve the desired effect by doing something like this in our app code:

```js
function makeAutoScope () {
  let scope = 0;

  return () => `cycle${scope++}`;
};

const autoScope = makeAutoScope();

const counter1 = isolate(Counter, autoScope())({DOM});
const counter2 = isolate(Counter, autoScope())({DOM});
```

I'm not really happy with any solution that requires a breaking code change to work.

I'll try fiddle around with peer dependencies and see if I can't get that style working, because at the moment, it seems like getting `isolate.reset()` to work is the best shot at getting this going without any breaking changes.

**Comment by Widdershin** [comment]
Oooh! I just solved it.

The `isolate.reset()` approach works if you pass `isolate` into `restart` instead of importing it inside of `cycle-restart` directly. Yay!

**Comment by staltz** [comment]
@Widdershin where is `isolate.reset()` actually implemented? Shouldn't it be in `@cycle/isolate`?

**Comment by Widdershin** [comment]
That's where it is implemented, I should have been more clear. https://github.com/cyclejs/isolate/pull/4
